### ISSUE TITLE
There are 0 values in the quality log in fish lab data that are not NA

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/jsp-data#12]
Presumably, that's because you filtered out all the other incidences of fish with a quality flag?

**Comment by jclgan** [comment]
No current fish in lab_data have quality_flag == "Y" because they were filtered out, correct. However, quality_log has lots of entries, such as for fish with modeled fork lengths or with measurements that were corrected.

**Comment by Br-Johnson** [comment]
Looks good!
