### ISSUE TITLE
Recording a seine event lat/lon when no fish were caught

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/jsp-data#15]
Judging by the data, it looks like we've been inconsistent in whether or not we record a seine lat/lon if it doesn't catch fish. 2019 it looks like we did a good job including lat/lons of sets with no fish. The issue is whether or not all the sets that did not catch fish are represented here. Ie. were we consistent enough in recording zeros for this to be useful to include?

**Comment by jclgan** [comment]
Seine lat/longs were consistently recorded in 2018-2019 regardless of fish retention.

In 2015, no data was recorded for a set with 0 sockeye
In 2016, JS only - if multiple sets were conducted, only the set that successfully retained fish had its data recorded. Unsure if "failed" sets meant 0 fish caught, or that they were botched (and thus shouldn't be counted)
In 2017, only 2 surveys had seines in which sets were attempted but had no data recorded if the sets had 0 fish caught/retained

**Comment by jclgan** [comment]
This can't be solved using oceanography gather coordinates, since if no fish were caught, sampling would have been conducted at the standard stations and not where the net was set.

**Comment by Br-Johnson** [comment]
This is a known issue now and because there were other consistencies in how a zero catch was recorded, a traditional catch per unit effort is never used. Instead, we use 'catch intensity' as a proxy for abundance which averages the number of each species caught when > 1 sockeye was caught (When sockeye  were caught we ALWAYS enumerated catch, but the same cant be said for other species, therefore we represent catch abundance of all other species in relation to the schools which contain sockeye)
