### ISSUE TITLE
Parasite loads within seasons

### ISSUE THREAD

**Issue by sarah-friesen** [HakaiInstitute/jsp-data#25]
Evaluating cumulative abundance/prevalence/etc of sea lice is interesting, but I would also be curious to compare parasite loads within seasons. If we were to break up the seasons into biweekly or monthly segments, we could look at how sea lice abundance etc varies within the season. Based partly on when a fish is passing through this area, its potential exposure to lice will vary, which might be important for stocks with different migration timing.

Given that fish migrating timing is likely shifting with climate change, I would be curious to see if/how temporal parasite loading is also shifting.

This is likely too detailed an analysis for the report.

**Comment by salmonsam** [comment]
Ooh, I like this approach though. I think it would be worth looking at a few of the different parameters on finer temporal scales so we can get at the importance of migration timing in determining fish health/chances of survival.

**Comment by Br-Johnson** [comment]
I don't think there's sufficient data within (recent) seasons to look at this with enough power
