### ISSUE TITLE
Add zooplankton taxonomy results to database

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/jsp-data#37]
There are zooplankton taxonomic species occurrences from JSP plankton tows, as well as stomach contents, that should be integrated in the Hakai JSP database via the data-integration-and-QC.Rmd script. 

They can be found here: https://catalogue.hakai.org/dataset/89b3c6d8-983b-48f4-a0b5-04eea65602f6 and https://catalogue.hakai.org/dataset/64f74489-b9a3-4e6f-9f25-be141b8e285c

**Comment by timvdstap** [comment]
Question to answer: include in the overall JSP OBIS record, or create new / separate data records for stomach contents & zooplankton taxonomic species occurrences?

**Comment by Br-Johnson** [comment]
@timvdstap I think gut contents are a different, discrete data set. We haven't combined gut contents from Sam James' (sockeye) and Vanessa Zahner's (pink and chum) MSc.'s yet because there hasn't been a need. The datasets are both published on the Hakai catalogue, just separate for now. There may be a need for a combined gut content data product in the future.

As for including in the overall JSP OBIS record, I suppose we could include the combined zooplankton results in OBIS! 

There's a need for a combined JSP zooplankton dataset for a current paper we're working on for sockeye foraging ecology and migration timing. So, I think it makes sense for me to do the initial part of this task which is consolidating the zooplankton data in the jsp-data repo. Then perhaps, you can include it in the OBIS record

**Comment by Br-Johnson** [comment]
Update: the paper is under review and came back for major revisions. Once the paper is accepted we will package the dataset up, host in a new git repository, create a new metadata record and then it could be transformed to be published into OBIS...

**Comment by Br-Johnson** [comment]
The article is published (pre-press abstract at https://doi.org/10.3354/meps14398) and the dataset is also published in the Hakai catalogue at https://doi.org/10.21966/tmch-5606

There is a zoopcomp.csv file in Sams data package which has some pretty amazing zooplankton taxonomy data that could contribute to a larger Hakai zoop OBIS record or even just be transformed to OBIS on its own. 

- [x] Talk about this with @timvdstap in relation to the Marine Ecology PG and whether this could contribute to a broader PG objective
