### ISSUE TITLE
#1 Salmon Sprint To Dos

### ISSUE THREAD

**Issue by timvdstap** [HakaiInstitute/jsp-data#41]
A list of items to do following our first Salmon Sprint (Sept 27 - 29, 2021): 

- [x] Update Field Sampling Protocol and archive it
- [x] #42
- [x] 2020/2021 [End of season report](https://docs.google.com/document/d/1UhUEZAzsfLDPDWqgnTN-Nzmrzox1OOKk/edit#heading=h.1fob9te) (finalize draft by the end of October)
- [X] Add hyperlinks to the [JSP Data Products Overview](https://lucid.app/lucidchart/7c6224b0-5613-485a-a36e-d8102c8a77de/edit?page=0_0#)
- [x] Update data-integration-and-QC.Rmd to download the most recent version from the Master JSP Tables Googlesheet (rather than having to download the specific sheets locally). 
- [x] Connect with UBC students and ask them to be involved in the Salmon Journal Club; update them on Hakai Data Mobilization Strategy / SOP, have them fill out Data Management Plans and Record(s). 
- [X] Ask Brian about an update to the [JSP Data Package Tracker](https://docs.google.com/spreadsheets/d/15fyAKNNhldctChLTtJhhxSj--km9jpynS5Qh9DIJ3Lk/edit?pli=1#gid=0), and include email addresses for all the Data Providers: TvdS emailed Brian on 10/8/2021
- [x] #43

**Comment by timvdstap** [comment]
Drafts in need of a final review: 

- [2020 and 2021 Field Sampling Protocol](https://docs.google.com/document/d/1Pcs3j4n24gpym2NCJY1QsxHWtPLmUPUB9c7WReBQJaY/edit#)
- [2020 and 2021 End of Season Report](https://docs.google.com/document/d/1UhUEZAzsfLDPDWqgnTN-Nzmrzox1OOKk/edit#)

**Comment by Br-Johnson** [comment]
Done!
