### ISSUE TITLE
Should Hakai metadata records be able to be published without a license?

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/jsp-data#48]
@timvdstap Luba and Keiths recent metadata records will never be made public because it's sensitive data. It will always be by request. In this case I imagine there should be no license attached to the dataset. But currently that's not an option in the metadata intake form. You can't save without a license.

Has this come up elsewhere? 

@n-a-t-e Can we just make it so there's no license required for the form to be saved?

**Comment by Br-Johnson** [comment]
Oops this should have been in the hakai-data repo

**Comment by timvdstap** [comment]
Ah interesting - I would say we should be able to publish 'metadata-only' records in the Hakai Catalogue, and indeed it seems that these should not have a license attached. It does kinda make me wonder whether there are currently other records in the catalogue that contain restricted data that should not have the CC-BY-4.0 license attached...

**Comment by Br-Johnson** [comment]
That's a good point. We could add that point to a review of the catalogue

**Comment by Br-Johnson** [comment]
@n-a-t-e mentioned that he could just add a 'None' category to the metaddata intake form

**Comment by timvdstap** [comment]
That sounds good. I think it might be valuable to add as guidance to the field that selecting 'None' is _not_ recommended, and should only be considered for metadata only records.

**Comment by Br-Johnson** [comment]
I created an issue for this at https://github.com/cioos-siooc/metadata-entry-form/issues/244 since we agree None should be an option
